# Generated by Django 4.1.3 on 2022-11-25 16:59

import django.core.validators
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('file', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='mediafiles', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('expiring_date', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
