# Generated by Django 4.1.3 on 2022-11-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='expiring_date',
            new_name='expiring_input',
        ),
        migrations.AddField(
            model_name='image',
            name='time_now',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
