# Generated by Django 4.1.3 on 2022-11-25 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_expiring_date_image_expiring_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='time_now',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 25, 18, 2, 19, 250578)),
        ),
    ]
