# Generated by Django 4.1.3 on 2022-11-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_time_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='expiring_input',
        ),
        migrations.RemoveField(
            model_name='image',
            name='time_now',
        ),
    ]
