# Generated by Django 4.1.3 on 2022-11-25 18:12

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_image_expiring_input_remove_image_time_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='time_created',
            field=models.DateTimeField(blank=True, default=images.models.get_time, null=True),
        ),
    ]
