# Generated by Django 4.1.3 on 2022-11-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='time_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
