# Generated by Django 4.1.3 on 2022-11-26 10:25

import django.core.validators
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_image_file2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file2',
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='mediafiles', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
