# Generated by Django 4.1.3 on 2022-11-26 11:07

import django.core.validators
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_alter_imageuploader_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploader',
            name='file',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='original_media', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
